### ISSUE TITLE
Entity Predict

### ISSUE THREAD

**Issue by TechAle** [gerald0mc/Mint-LEAKED-0.1.1#10]
Who tf coded entity predict?
                    
    switch (attackAmount.getValue()) {

                    case 1:
 
                        attackEntity(entityId + 1);
 
                        break;
 
                    case 2:
 
                        attackEntity(entityId + 1);
 
                        attackEntity(entityId + 2);
 
                        break;
 
                    case 3:
 
                        attackEntity(entityId + 1);
 
                        attackEntity(entityId + 2);
 
                        attackEntity(entityId + 3);
 
                        break;
 
                    case 4:
 
                        attackEntity(entityId + 1);
 
                        attackEntity(entityId + 2);
 
                        attackEntity(entityId + 3);
 
                        attackEntity(entityId + 4);
 
                        break;
 
                    case 5:
 
                        attackEntity(entityId + 1);
 
                        attackEntity(entityId + 2);
 
                        attackEntity(entityId + 3);
 
                        attackEntity(entityId + 4);
 
                        attackEntity(entityId + 5);
 
                        break;
 
 
                }
Do you know that for exists?

**Comment by urelNiP** [comment]
it will be faster ur ca in openanarcy or eliteanarchy idk

**Comment by gerald0mc** [comment]
> Who tf coded entity predict?
> 
> ```
> switch (attackAmount.getValue()) {
> 
>                 case 1:
> 
>                     attackEntity(entityId + 1);
> 
>                     break;
> 
>                 case 2:
> 
>                     attackEntity(entityId + 1);
> 
>                     attackEntity(entityId + 2);
> 
>                     break;
> 
>                 case 3:
> 
>                     attackEntity(entityId + 1);
> 
>                     attackEntity(entityId + 2);
> 
>                     attackEntity(entityId + 3);
> 
>                     break;
> 
>                 case 4:
> 
>                     attackEntity(entityId + 1);
> 
>                     attackEntity(entityId + 2);
> 
>                     attackEntity(entityId + 3);
> 
>                     attackEntity(entityId + 4);
> 
>                     break;
> 
>                 case 5:
> 
>                     attackEntity(entityId + 1);
> 
>                     attackEntity(entityId + 2);
> 
>                     attackEntity(entityId + 3);
> 
>                     attackEntity(entityId + 4);
> 
>                     attackEntity(entityId + 5);
> 
>                     break;
> 
> 
>             }
> ```
> 
> Do you know that for exists?

this is used on stuff like stairs it predicts shit

**Comment by TechAle** [comment]
Stairs predict? This is bad coded entity predict lmao +  i dont find any correlations with stairs predict
It's a "i dont know what a for is, i'll use a switch", one of the worst things i have ever read.

**Comment by notperry1234567890** [comment]
> Stairs predict? This is bad coded entity predict lmao + i dont find any correlations with stairs predict It's a "i dont know what a for is, i'll use a switch", one of the worst things i have ever read.

Ur expecting these 12 yr OyVey skidding to know how to code in java kek.

**Comment by ProfKambing** [comment]
> Who tf coded entity predict?
> 
> ```
> switch (attackAmount.getValue()) {
> 
>                 case 1:
> 
>                     attackEntity(entityId + 1);
> 
>                     break;
> 
>                 case 2:
> 
>                     attackEntity(entityId + 1);
> 
>                     attackEntity(entityId + 2);
> 
>                     break;
> 
>                 case 3:
> 
>                     attackEntity(entityId + 1);
> 
>                     attackEntity(entityId + 2);
> 
>                     attackEntity(entityId + 3);
> 
>                     break;
> 
>                 case 4:
> 
>                     attackEntity(entityId + 1);
> 
>                     attackEntity(entityId + 2);
> 
>                     attackEntity(entityId + 3);
> 
>                     attackEntity(entityId + 4);
> 
>                     break;
> 
>                 case 5:
> 
>                     attackEntity(entityId + 1);
> 
>                     attackEntity(entityId + 2);
> 
>                     attackEntity(entityId + 3);
> 
>                     attackEntity(entityId + 4);
> 
>                     attackEntity(entityId + 5);
> 
>                     break;
> 
> 
>             }
> ```
> 
> Do you know that for exists?

zprestige
