### ISSUE TITLE
hot

### ISSUE THREAD

**Issue by LiquidSmokeBalls** [gerald0mc/Mint-LEAKED-0.1.1#2]
watch master720 put a pullrequest saying update mcmod.info 😐

**Comment by sarnthilIsHorny** [comment]
> watch master720 put a pullrequest saying update mcmod.info 😐

*master7720 😂

**Comment by ssllllll** [comment]
> watch master720 put a pullrequest saying update mcmod.info 😐

YEAH AHHAHAHAHA

**Comment by notperry1234567890** [comment]
> watch master720 put a pullrequest saying update mcmod.info 😐

TRUE LOL

**Comment by bush-did-711** [comment]
> watch master720 put a pullrequest saying update mcmod.info 😐

LOL

**Comment by bush-did-711** [comment]
and then proceed to make it 10x worse

**Comment by gerald0mc** [comment]
for sure
