### ISSUE TITLE
HAHAHAHA CANT EVEN TAKE BAITS

### ISSUE THREAD

**Issue by ProfKambing** [gerald0mc/Mint-LEAKED-0.1.1#3]
omg imso mad getting baited by zprestigeso i leak his masterpiece

**Comment by ssllllll** [comment]
omg imso mad getting my """masterpiece""" leaked and imma open an issue talking about it to see if someone cares 🤓

**Comment by ssllllll** [comment]
@gerald0mc thanks for leaking this, now mint devs cant stop saying their shit is a """"""""""masterpiece""""""""""

**Comment by ProfKambing** [comment]
who are u

**Comment by ssllllll** [comment]
![image](https://user-images.githubusercontent.com/86989232/141603905-8f21df3a-e78b-4e6c-a9ac-0f5dd90d7ba0.png)

**Comment by ssllllll** [comment]
people from malaisya is so cringe

**Comment by ProfKambing** [comment]
said the spanish ong

**Comment by ProfKambing** [comment]
total nn

**Comment by ssllllll** [comment]
> said the spanish ong

im proud to be spanish, when someone remembers that u r from malaisya u start crying 😹 🚬

**Comment by ProfKambing** [comment]
proof?

**Comment by gerald0mc** [comment]
> omg imso mad getting baited by zprestigeso i leak his masterpiece

🚬

**Comment by GentlemanMC** [comment]
Just Smoked that mint pack 🚬
