### ISSUE TITLE
Cope and seethe mald

### ISSUE THREAD

**Issue by GentlemanMC** [gerald0mc/Mint-LEAKED-0.1.1#7]
Stay mad kambing
Stay mad _zPrestige

Leaked client 2.0
Leaked mint (client 3.9)

Smoked that retarded pack 🚬

**Comment by urelNiP** [comment]
agreed

**Comment by gerald0mc** [comment]
> Stay mad kambing Stay mad _zPrestige
> 
> Leaked client 2.0 Leaked mint (client 3.9)
> 
> Smoked that retarded pack 🚬

based
